Repository flashbots/mev-boost, pull requests merged in 2022-10, with the labels that each got.

#365 accept gzip encoding
  server/utils.go
  server/utils_test.go
Labels: next up, discuss, in development

#299 Validate blockhash that the relayer responds with
  server/mock_relay.go
  server/service.go
  server/service_test.go
Labels: next up, code complete

#274 Min bid
  cli/main.go
  cli/main_test.go
  server/service.go
  server/service_test.go
Labels: discuss, in development, in review :mag:

#379 Minor release fixes for v1.4.0
  .github/workflows/release.yaml
  .github/workflows/tests.yml
  RELEASE.md
  cli/main.go
Labels: next up, code complete

#303 Run gocritic linter
  .golangci.yml
  CONTRIBUTING.md
  Makefile
  cli/main.go
  server/mock_relay.go
Labels: next up, code complete, in review :mag:
